version: '3'

services:
  webserver:
    image: node
    container_name: node
    build: .
    ports:
      - 8091:8091
    command: "npm run serve"
  
  cypress:    
    image: cypress
    build: ./src/AutomationTests
    container_name: cypress
    depends_on:
      - webserver
    environment:
      - CYPRESS_baseUrl=http://webserver:8091  
    working_dir: /usr/src/app/AutomationTests
    volumes:
      - ./:/e2e